# Generated by Django 5.0.3 on 2024-04-04 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bird',
            old_name='breed',
            new_name='family',
        ),
    ]
