# Generated by Django 5.0.3 on 2024-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='species',
            field=models.ManyToManyField(to='main_app.specie'),
        ),
    ]
